## Basic Theme Info
name: The Metropolitan Theatre
description: New website for The Metropolitan Theatre, located in downtown Morgantown, WV. Supported by the WVU College of Creative Arts. CMS is Cleanslate, a WVU platform. Hosted by WVU.


## Attributes, Data and Variables
custom_site_attributes:
  # For Google Search Console
  - google_site_verification

## Template Config
# Specify which templates show up by default when creating a page
default_templates:
  content: backpage
  blog: blog_index
  article: blog_article
  error: backpage

## Optimizations
css:
  # Turn CSS compression on/off.
  compress: true
js:
  # Turn JavaScript compression and mangling on/off
  compress: true
  mangle: true
